//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public string UserId { get; set; }
        public string AccountName { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string IDNumber { get; set; }
        public Nullable<int> Sex { get; set; }
        public string RoleId { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
